### PR TITLE
actions: fix shouldScrobble syntax error

### PR DESCRIPTION
**Pull request by Ivshti**
give me collab access as well Branza

(expecting an image reaction to that)

### CODE REVIEW

**Comment by Ivshti** [comment]
you're quick

**Comment by jaruba** [comment]
giphy 3

**Comment by jaruba** [comment]
i'm not sure this PR is good though, what was the error you wore referring to?

**Comment by Ivshti** [comment]
Does this syntax look fine to you?

This is wrong js syntax. It breaks powder completely

**Comment by jaruba** [comment]
ah, it should be:

```
var shouldScrobble = traktUtil.loggedIn ? ls.isSet('traktScrobble') ? ls('traktScrobble') : true : false;
```

**Comment by Ivshti** [comment]
now it's correct, but isn't beautiful

Should be
```javascript
var shouldScrobble = ls.isSet('traktScrobble') ? ls('traktScrobble') : traktUtil.loggedIn
```

Simply: if it's set in settings, use that. Otherwise, use traktUtil.loggedIn

**Comment by jaruba** [comment]
Without `traktUtil.loggedIn` it can't scrobble at all, so that needs to be the first `if`..

And if `traktScrobble` isn't set at all, it needs to default to `true`, I don't think it can get any more beautiful then:

```
var shouldScrobble = traktUtil.loggedIn ? ls.isSet('traktScrobble') ? ls('traktScrobble') : true : false;
```

Unless I make some util that checks `localStorage` params and defaults them to `true`. (this being a common enough case for my settings)

In which case it would look something like:

```
var shouldScrobble = traktUtil.loggedIn ? opts.setting('traktScrobble') : false;
```

**Comment by Ivshti** [comment]
traktUtil.loggedIn && (ls.isSet('traktScrobble') ? ls('traktScrobble') : true)

**Comment by jaruba** [comment]
That's indeed an improvement :)

You can change it and merge if you want, i'll still prob do a `opts` util soon to prettify things even further.

**Comment by Ivshti** [comment]
@jaruba done

**Pull request merged**
