### PR TITLE
allow m4v + clarify registerUtil's mess

### PR DESCRIPTION
**Pull request by vankasteelj**

### CODE REVIEW

**Comment by jaruba** [comment]
I have nothing against this, it's correctly implemented. I'm just not merging yet because it will be easier to solve merge conflicts from this PR then from mine and luigi's branches. (which are huge and will need to be merged too)

**Comment by vankasteelj** [comment]
Oh, we're waiting on luigi? Well then:

**Comment by vankasteelj** [comment]
hard1
hard2
hard3
hard4

**Pull request merged**
